/*
Copyright The Longhorn Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta2

// QosLimitsApplyConfiguration represents a declarative configuration of the QosLimits type for use
// with apply.
//
// QosLimits maps to SPDK's bdev_set_qos_limit parameters one-to-one. SPDK
// enforces each as a separate token bucket; clients can mix-and-match
// (e.g. cap aggregate IOPS but only writes for bandwidth).
type QosLimitsApplyConfiguration struct {
	RwIOsPerSec *int64 `json:"rwIOsPerSec,omitempty"`
	RwMBPerSec  *int64 `json:"rwMBPerSec,omitempty"`
	RMBPerSec   *int64 `json:"rMBPerSec,omitempty"`
	WMBPerSec   *int64 `json:"wMBPerSec,omitempty"`
}

// QosLimitsApplyConfiguration constructs a declarative configuration of the QosLimits type for use with
// apply.
func QosLimits() *QosLimitsApplyConfiguration {
	return &QosLimitsApplyConfiguration{}
}

// WithRwIOsPerSec sets the RwIOsPerSec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RwIOsPerSec field is set to the value of the last call.
func (b *QosLimitsApplyConfiguration) WithRwIOsPerSec(value int64) *QosLimitsApplyConfiguration {
	b.RwIOsPerSec = &value
	return b
}

// WithRwMBPerSec sets the RwMBPerSec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RwMBPerSec field is set to the value of the last call.
func (b *QosLimitsApplyConfiguration) WithRwMBPerSec(value int64) *QosLimitsApplyConfiguration {
	b.RwMBPerSec = &value
	return b
}

// WithRMBPerSec sets the RMBPerSec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RMBPerSec field is set to the value of the last call.
func (b *QosLimitsApplyConfiguration) WithRMBPerSec(value int64) *QosLimitsApplyConfiguration {
	b.RMBPerSec = &value
	return b
}

// WithWMBPerSec sets the WMBPerSec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WMBPerSec field is set to the value of the last call.
func (b *QosLimitsApplyConfiguration) WithWMBPerSec(value int64) *QosLimitsApplyConfiguration {
	b.WMBPerSec = &value
	return b
}
